version: '3.8'

services:
  gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
      - BACKEND_URL=${BACKEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - POLICY_PATH=${POLICY_PATH}
      - REDIS_ADDR=${REDIS_ADDR}
    depends_on:
      - redis
      - mock-backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mock-backend:
    image: python:3.9-alpine
    volumes:
      - ./scripts/mock_backend.py:/app/mock_backend.py
    command: python3 /app/mock_backend.py
    ports:
      - "8081:8081"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # ports:
    #   - "9095:9090"
